package spotinst

spotinst_aws_elastigroup :: {
	when?: string
	with_items?: [...string]
	connection?: string
	become?:     bool
	vars?: {...}
	register?: string
	tags?: [...string]
	notify?: string | [...string]
	name?:   string
	spotinst_aws_elastigroup: {
		on_demand_instance_type:                             string
		scheduled_tasks?:                                    string
		tenancy?:                                            string
		terminate_at_end_of_billing_hour?:                   bool
		up_scaling_policies?:                                string
		health_check_unhealthy_duration_before_replacement?: string
		tags?:                                               string
		target_tracking_policies?:                           string
		persistence?:                                        string
		ebs_optimized?:                                      bool
		fallback_to_od?:                                     bool
		load_balancers?:                                     string
		risk?:                                               string
		down_scaling_policies?:                              string
		spin_up_time?:                                       string
		image_id:                                            string
		elastic_ips?:                                        string
		on_demand_count?:                                    string
		ecs?:                                                string
		min_size:                                            string
		signals?:                                            string
		account_id?:                                         string
		block_device_mappings?:                              string
		ebs_volume_pool?:                                    string
		name:                                                string
		product:                                             string
		right_scale?:                                        string
		security_group_ids:                                  string
		state?:                                              string
		availability_zones:                                  string
		opsworks?:                                           string
		health_check_type?:                                  string
		target:                                              string
		wait_timeout?:                                       string
		monitoring:                                          string
		iam_role_name?:                                      string
		key_pair:                                            string
		draining_timeout?:                                   string
		roll_config?:                                        string
		shutdown_script?:                                    string
		max_size:                                            string
		credentials_path?:                                   string
		id?:                                                 string
		kubernetes?:                                         string
		lifetime_period?:                                    string
		availability_vs_cost:                                string
		rancher?:                                            string
		unit:                                                string
		utilize_reserved_instances?:                         bool
		network_interfaces?:                                 string
		wait_for_instances?:                                 bool
		chef?:                                               string
		mesosphere?:                                         string
		spot_instance_types:                                 string
		uniqueness_by?:                                      string
		user_data?:                                          string
		ignore_changes?:                                     string
		iam_role_arn?:                                       string
		target_group_arns?:                                  string
		health_check_grace_period?:                          string
	}
}
